// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHCh2PB4brRbfbMCZRn39zAzP6pepzLTY',
    appId: '1:1003956420517:web:3480c06ac0675c2707b24c',
    messagingSenderId: '1003956420517',
    projectId: 'sugariqf',
    authDomain: 'sugariqf.firebaseapp.com',
    storageBucket: 'sugariqf.firebasestorage.app',
    measurementId: 'G-5NVL5ZL439',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3kV9HVx9tUA0WGlmkcweYABGWCbuGMk4',
    appId: '1:1003956420517:android:00206a10173ddc5807b24c',
    messagingSenderId: '1003956420517',
    projectId: 'sugariqf',
    storageBucket: 'sugariqf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo1XaKsE_vjj0wxabSXSCejZ4Oj67kslQ',
    appId: '1:1003956420517:ios:04a82fc047beb5ba07b24c',
    messagingSenderId: '1003956420517',
    projectId: 'sugariqf',
    storageBucket: 'sugariqf.firebasestorage.app',
    iosBundleId: 'com.example.sugarIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo1XaKsE_vjj0wxabSXSCejZ4Oj67kslQ',
    appId: '1:1003956420517:ios:04a82fc047beb5ba07b24c',
    messagingSenderId: '1003956420517',
    projectId: 'sugariqf',
    storageBucket: 'sugariqf.firebasestorage.app',
    iosBundleId: 'com.example.sugarIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHCh2PB4brRbfbMCZRn39zAzP6pepzLTY',
    appId: '1:1003956420517:web:c687605586806e7207b24c',
    messagingSenderId: '1003956420517',
    projectId: 'sugariqf',
    authDomain: 'sugariqf.firebaseapp.com',
    storageBucket: 'sugariqf.firebasestorage.app',
    measurementId: 'G-LG1DHGM4LD',
  );

}